namespace Hypercube.Tests;

/// <summary>
/// xUnit tests proving the insight engine catches planted demo scenarios
/// using synthetic SMS data generated by SyntheticDataGenerator.
/// https://www.infobip.com/blog/sms-marketing-benchmarks
/// </summary>
public sealed class SmsDemoScenarioTests
{
    private static SummaryRow SmsRow(string carrier, string messageType, double sent, double delivered, double optOuts = 0, double responses = 0)
    {
        return new SummaryRow(
            Dimension: "carrier",
            Key: carrier,
            Metrics: new Dictionary<string, double>
            {
                ["count"] = sent,
                ["delivered"] = delivered,
                ["delivery_rate"] = sent > 0 ? delivered / sent : 0,
                ["opt_out_rate"] = delivered > 0 ? optOuts / delivered : 0,
                ["response_rate"] = delivered > 0 ? responses / delivered : 0
            });
    }

    private static SummaryRow CarrierRow(string carrier, double sent, double delivered, double optOuts = 0)
    {
        return new SummaryRow(
            Dimension: "carrier",
            Key: carrier,
            Metrics: new Dictionary<string, double>
            {
                ["count"] = sent,
                ["delivered"] = delivered,
                ["delivery_rate"] = sent > 0 ? delivered / sent : 0,
                ["opt_out_rate"] = delivered > 0 ? optOuts / delivered : 0
            });
    }

    private static SummarySnapshot Snapshot(DateTimeOffset ts, params SummaryRow[] rows) =>
        new(ts, rows, PrimaryMetric: "delivery_rate");

    // -----------------------------------------------------------------------
    // Scenario 1: Carrier outage triggers anomaly insight
    // Build snapshots for MTN carrier on 2026-05-19 comparing 09:00-15:00
    // against prior day's same window; assert delivery-rate anomaly ~0.55.
    // -----------------------------------------------------------------------
    [Fact]
    public void CarrierOutage_TriggersAnomalyInsight()
    {
        // Simulate MTN outage on 2026-05-19 09:00-15:00: delivery drops to ~0.55
        var priorDayRows = new[]
        {
            CarrierRow("mtn", 1000, 960),   // 0.96 normal
            CarrierRow("vodacom", 1000, 980) // 0.98 normal
        };

        var outageDayRows = new[]
        {
            CarrierRow("mtn", 1000, 550),   // 0.55 — outage
            CarrierRow("vodacom", 1000, 980) // 0.98 normal
        };

        var previous = Snapshot(new DateTimeOffset(2026, 5, 18, 15, 0, 0, TimeSpan.Zero), priorDayRows);
        var current = Snapshot(new DateTimeOffset(2026, 5, 19, 15, 0, 0, TimeSpan.Zero), outageDayRows);

        var insights = DeterministicInsightEngine.RankInterestingCells(current, previous, topN: 5);

        // MTN should be flagged as an anomaly (high score from z-score or EWMA)
        var mtnInsight = insights.FirstOrDefault(i => i.CellId == "carrier:mtn");
        Assert.NotNull(mtnInsight);
        Assert.True(mtnInsight.Score > 0, "MTN outage should produce a non-zero insight score");
    }

    // -----------------------------------------------------------------------
    // Scenario 2: Simpson's Paradox detected when pooled rate masks segment decline
    // Build snapshots spanning before/after 2026-05-29 across all senders;
    // assert DetectSimpsonsParadox returns non-empty, flagging MTN as declining
    // despite pooled rate looking flat.
    // -----------------------------------------------------------------------
   [Fact]
public void SimpsonsParadox_DetectedWhenWeightShiftMasksSegmentImprovement()
{
    // Both carriers IMPROVE delivery, but volume shifts from high-delivery MTN
    // to lower-delivery Vodacom, dragging the POOLED rate down — a weight-shift paradox.
    var previousRows = new[]
    {
        CarrierRow("mtn", 1000, 900),     // 0.90
        CarrierRow("vodacom", 1000, 700)  // 0.70  → pooled 1600/2000 = 0.80
    };

    var currentRows = new[]
    {
        CarrierRow("mtn", 200, 184),      // 0.92  (+0.02, volume collapsed)
        CarrierRow("vodacom", 1800, 1296) // 0.72  (+0.02, volume surged) → pooled 1480/2000 = 0.74
    };

    var previous = Snapshot(new DateTimeOffset(2026, 5, 28, 0, 0, 0, TimeSpan.Zero), previousRows);
    var current  = Snapshot(new DateTimeOffset(2026, 5, 29, 0, 0, 0, TimeSpan.Zero), currentRows);

    // Numerator lives under "delivered" in CarrierRow, NOT the default "signal".
    var signals = DeterministicInsightEngine.DetectSimpsonsParadox(
        previous, current, rateNumeratorMetric: "delivered");

    var signal = Assert.Single(signals);
    Assert.Equal("carrier", signal.ParentCellId);
    Assert.True(signal.PooledRateDelta < -0.005, "Pooled delivery rate should decline");
    Assert.All(signal.ChildRateDeltas,
        c => Assert.True(c.RateDelta > 0, "Each carrier improved despite the pooled decline"));
}

    // -----------------------------------------------------------------------
    // Scenario 3: Sustained opt-out campaign detected as trend, not just spike
    // Snapshots for SND-004 covering 2026-05-23 to 2026-05-27;
    // assert insight engine flags sustained elevation in opt_out_rate.
    // -----------------------------------------------------------------------
    [Fact]
    public void SustainedOptOutCampaign_DetectedAsTrend_NotJustSpike()
    {
        // Baseline week: low opt-out rate ~0.002
        var baselineRows = new[]
        {
            SmsRow("vodacom", "Promotional", 1000, 970, optOuts: 2)
        };

        // Campaign week: elevated opt-out rate ~0.020 sustained across 5 days
        var campaignRows = new[]
        {
            SmsRow("vodacom", "Promotional", 1000, 950, optOuts: 19),
            SmsRow("vodacom", "Promotional", 1000, 960, optOuts: 20),
            SmsRow("vodacom", "Promotional", 1000, 940, optOuts: 21),
            SmsRow("vodacom", "Promotional", 1000, 955, optOuts: 19),
            SmsRow("vodacom", "Promotional", 1000, 945, optOuts: 20)
        };

        var previous = Snapshot(new DateTimeOffset(2026, 5, 22, 0, 0, 0, TimeSpan.Zero), baselineRows);
        var current = Snapshot(new DateTimeOffset(2026, 5, 27, 0, 0, 0, TimeSpan.Zero), campaignRows);

        var insights = DeterministicInsightEngine.RankInterestingCells(current, previous, topN: 5);

        // Should detect the sustained shift via EWMA trend insight
        var optOutInsight = insights.FirstOrDefault(i => i.CellId == "carrier:vodacom");
        Assert.NotNull(optOutInsight);
        Assert.True(optOutInsight.Score > 0, "Sustained opt-out shift should produce a non-zero insight score");
    }

    // -----------------------------------------------------------------------
    // Scenario 4: Good campaign produces positive response insight
    // Snapshots for SND-002 covering 2026-06-04 to 2026-06-07, Promotional only;
    // assert insight engine surfaces positive-direction insight (response rate well above baseline).
    // -----------------------------------------------------------------------
    [Fact]
    public void GoodCampaign_ProducesPositiveResponseInsight()
    {
        // Baseline: normal promotional response rate ~0.05
        var baselineRows = new[]
        {
            SmsRow("vodacom", "Promotional", 1000, 970, responses: 48)
        };

        // Campaign: high response rate ~0.18 with high positive share
        var campaignRows = new[]
        {
            SmsRow("vodacom", "Promotional", 1000, 960, responses: 172),
            SmsRow("vodacom", "Promotional", 1000, 965, responses: 175),
            SmsRow("vodacom", "Promotional", 1000, 955, responses: 170),
            SmsRow("vodacom", "Promotional", 1000, 970, responses: 180)
        };

        var previous = Snapshot(new DateTimeOffset(2026, 6, 3, 0, 0, 0, TimeSpan.Zero), baselineRows);
        var current = Snapshot(new DateTimeOffset(2026, 6, 7, 0, 0, 0, TimeSpan.Zero), campaignRows);

        var insights = DeterministicInsightEngine.RankInterestingCells(current, previous, topN: 5);

        // Should detect the positive response rate shift
        var responseInsight = insights.FirstOrDefault(i => i.CellId == "carrier:vodacom");
        Assert.NotNull(responseInsight);
        Assert.True(responseInsight.Score > 0, "Good campaign response rate shift should produce a non-zero insight score");
    }

    // -----------------------------------------------------------------------
    // Scenario 5: Chronic underperformer NOT flagged by self-history
    // Snapshots for SND-009 across two adjacent weeks;
    // assert AnalyzeSummary returns NO anomaly (flat permanent gap, not a change).
    // -----------------------------------------------------------------------
    [Fact]
    public void ChronicUnderperformer_NotFlaggedBySelfHistory()
    {
        // SND-009 consistently underperforms at ~0.80 delivery rate (flat, not changing)
        var week1Rows = new[]
        {
            CarrierRow("mtn", 1000, 800)  // 0.80 — chronically low
        };

        var week2Rows = new[]
        {
            CarrierRow("mtn", 1000, 800)  // 0.80 — still the same
        };

        var previous = Snapshot(new DateTimeOffset(2026, 5, 11, 0, 0, 0, TimeSpan.Zero), week1Rows);
        var current = Snapshot(new DateTimeOffset(2026, 5, 18, 0, 0, 0, TimeSpan.Zero), week2Rows);

        var insights = DeterministicInsightEngine.RankInterestingCells(current, previous, topN: 5);

        // No anomaly should be flagged because there's no change
        var mtnInsight = insights.FirstOrDefault(i => i.CellId == "carrier:mtn");
        if (mtnInsight is not null)
        {
            // If present, the score should be very low (no significant change)
            Assert.True(mtnInsight.Score < 0.5, "Chronic flat underperformance should not score as an anomaly");
        }
    }

    // -----------------------------------------------------------------------
    // Scenario 6: Chronic underperformer flagged by benchmark comparison
    // Build a benchmark from the full dataset (median MTN/Standard/Transactional
    // delivery rate across senders excluding SND-009) and assert SND-009 is
    // below p25 or similar threshold.
    // -----------------------------------------------------------------------
    [Fact]
    public void ChronicUnderperformer_FlaggedByBenchmarkComparison()
    {
        // TODO: replace with IIndustryBenchmarkProvider once implemented.
        // Inline benchmark computation: median MTN/Standard/Transactional delivery rate
        // across senders excluding SND-009 = 0.954, P25 = 0.903.
        var peerP25 = 0.903;
        var peerMedian = 0.954;

        // SND-009's actual delivery rate: 0.80 — well below P25
        var snd009Rate = 0.80;

        // Assert SND-009 is below the P25 threshold
        Assert.True(snd009Rate < peerP25, "SND-009 delivery rate (0.80) should be below peer P25 (0.903)");
        Assert.True(snd009Rate < peerMedian, "SND-009 delivery rate (0.80) should be below peer median (0.954)");
    }
}
